services:
  - type: web
    name: alumni-association-platform
    env: python
    repo: https://github.com/INFO3604-AlumniAssociationProject/AlumniAssociationPlatformProject
    plan: free
    branch: main
    rootDir: Backend
    buildCommand: |
      pip install -r requirements.txt
      cd ../Frontend && npm install --legacy-peer-deps && npm run build
    startCommand: gunicorn wsgi:app --bind 0.0.0.0:$PORT
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: FRONTEND_ORIGINS
        value: https://alumni-association-platform.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: alumni-db
          property: connectionString

databases:
  - name: alumni-db
    plan: free